# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metric.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metric.proto',
  package='metric',
  serialized_pb=_b('\n\x0cmetric.proto\x12\x06metric\"f\n\x06Metric\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x02\x12\x11\n\ttimestamp\x18\x03 \x02(\x02\x12\x11\n\tprecision\x18\x04 \x02(\x05\x12\x0c\n\x04host\x18\x05 \x02(\t\x12\x0b\n\x03ttl\x18\x06 \x02(\x02\"-\n\x0bMetricBatch\x12\x1e\n\x06metric\x18\x01 \x03(\x0b\x32\x0e.metric.Metric')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_METRIC = _descriptor.Descriptor(
  name='Metric',
  full_name='metric.Metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='metric.Metric.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='metric.Metric.value', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='metric.Metric.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='precision', full_name='metric.Metric.precision', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='metric.Metric.host', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='metric.Metric.ttl', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=126,
)


_METRICBATCH = _descriptor.Descriptor(
  name='MetricBatch',
  full_name='metric.MetricBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metric', full_name='metric.MetricBatch.metric', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=173,
)

_METRICBATCH.fields_by_name['metric'].message_type = _METRIC
DESCRIPTOR.message_types_by_name['Metric'] = _METRIC
DESCRIPTOR.message_types_by_name['MetricBatch'] = _METRICBATCH

Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), dict(
  DESCRIPTOR = _METRIC,
  __module__ = 'metric_pb2'
  # @@protoc_insertion_point(class_scope:metric.Metric)
  ))
_sym_db.RegisterMessage(Metric)

MetricBatch = _reflection.GeneratedProtocolMessageType('MetricBatch', (_message.Message,), dict(
  DESCRIPTOR = _METRICBATCH,
  __module__ = 'metric_pb2'
  # @@protoc_insertion_point(class_scope:metric.MetricBatch)
  ))
_sym_db.RegisterMessage(MetricBatch)


# @@protoc_insertion_point(module_scope)
