# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='metrics.proto',
  package='metric',
  serialized_pb='\n\rmetrics.proto\x12\x06metric\"f\n\x06Metric\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x02\x12\x11\n\ttimestamp\x18\x03 \x02(\x02\x12\x11\n\tprecision\x18\x04 \x02(\x05\x12\x0c\n\x04host\x18\x05 \x02(\t\x12\x0b\n\x03ttl\x18\x06 \x02(\x02\"-\n\x0bMetricBatch\x12\x1e\n\x06metric\x18\x01 \x03(\x0b\x32\x0e.metric.Metric')




_METRIC = descriptor.Descriptor(
  name='Metric',
  full_name='metric.Metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='path', full_name='metric.Metric.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='metric.Metric.value', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='metric.Metric.timestamp', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='precision', full_name='metric.Metric.precision', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='host', full_name='metric.Metric.host', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ttl', full_name='metric.Metric.ttl', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=25,
  serialized_end=127,
)


_METRICBATCH = descriptor.Descriptor(
  name='MetricBatch',
  full_name='metric.MetricBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='metric', full_name='metric.MetricBatch.metric', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=174,
)

_METRICBATCH.fields_by_name['metric'].message_type = _METRIC
DESCRIPTOR.message_types_by_name['Metric'] = _METRIC
DESCRIPTOR.message_types_by_name['MetricBatch'] = _METRICBATCH

class Metric(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METRIC
  
  # @@protoc_insertion_point(class_scope:metric.Metric)

class MetricBatch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METRICBATCH
  
  # @@protoc_insertion_point(class_scope:metric.MetricBatch)

# @@protoc_insertion_point(module_scope)
